language: ruby
dist: xenial
rvm:
  - 2.6.1
notifications:
  email:
    recipients:
      - okkez000@gmail.com
      - zn@mbf.nifty.com
      - sho.hsmt@gmail.com
  irc:
    channels:
      - "chat.freenode.net#ruby-ja"
    on_success: change # [always|never|change] # default: always
    on_failure: always # [always|never|change] # default: always
    template:
      - "%{message} by @%{author}: See %{build_url}"
before_install:
  - 'go get github.com/client9/misspell/...'
script:
  - 'bundle exec rake'
  - '$GOPATH/bin/misspell -error -i addopt $(git ls-files | grep -vF "refm/doc/news/1.8.4.rd")'
